spring.application.name=colis-system

spring.data.mongodb.uri=mongodb://localhost:27017/colis_db

logging.level.org.springframework.security=DEBUG

jwt.secret=CeciEstUneCleSecreteTresLongueEtSecuriseePourLeProjetColis123456

# Expiration in 24 hours (in milliseconds) = 86400000 ms
jwt.expiration=86400000